// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTN1wWaHM7pUYFtDBdg04YNLbuI1ERM1k',
    appId: '1:178037221731:web:ba490dde0cc0493b4a0b56',
    messagingSenderId: '178037221731',
    projectId: 'handplay-718c1',
    authDomain: 'handplay-718c1.firebaseapp.com',
    storageBucket: 'handplay-718c1.firebasestorage.app',
    measurementId: 'G-WCZ646TLHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw45O0BwmgqAFRVYyaPhx6aZ6tg1nlohE',
    appId: '1:178037221731:android:0ad7ef58f79012f74a0b56',
    messagingSenderId: '178037221731',
    projectId: 'handplay-718c1',
    storageBucket: 'handplay-718c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDplre1pbHPxmUEEw_JGsZVOrm9Uqhq5t8',
    appId: '1:178037221731:ios:bb64a4d5996fb2a74a0b56',
    messagingSenderId: '178037221731',
    projectId: 'handplay-718c1',
    storageBucket: 'handplay-718c1.firebasestorage.app',
    iosBundleId: 'com.example.handplay',
  );
}
